 const accessories = [
  { name: 'Door Exit Metal Square',
    price: 850, 
    warranty: '6 months',
  },
  { name: 'AL-280',
    price: 4400, 
    warranty: '12 months',
  },
  { name: 'AL-280PZ/PL',
    price: 2400, 
    warranty: '12 months',
  },
  { name: 'RPS',
    price: 2800, 
    warranty: '6 months',
  },
  { name: 'EBG',
    price: 2800, 
    warranty: '6 months',
  },
  //Optional Accessories
  { name: 'Small Push Button (reception)',
    price: 150, 
    warranty: 'none',
  },
  { name: 'Slim Push Button',
    price: 800, 
    warranty: 'none',
  },
  { name: 'FA210 Temperature Detection Module',
    price: 9500, 
    warranty: 'none',
  },
  { name: 'Proximity Card RFID',
    price: 80, 
    warranty: 'none',
  },
  { name: 'U-bracket (for frameless Door)',
    price: 1200, 
    warranty: 'none',
  },
  { name: 'Dropbolt with L&Z Bracket',
    price: 8200, 
    warranty: 'none',
  },
  { name: 'Aluminum U-Bracket for Dropbolt',
    price: 1500, 
    warranty: 'none',
  },
  { name: 'Drop bolt lock for fully frame less glass door',
    price: 6500, 
    warranty: 'none',
  },
  { name: 'RPS 12Vdc 5A Regulated Power Supply (with backup battery)',
    price: 4500, 
    warranty: 'none',
  },
  { name: 'Fr1200 Biometrics Scanner with Built-in Card Reader',
    price: 8500, 
    warranty: '12 months',
  }, 
  { name: 'K1 Touch Free Push to Exit',
    price: 1200, 
    warranty: 'none',
  }, 
  { name: 'WTTTX KIT2',
    price: 1500, 
    warranty: 'none',
  }, 
  { name: 'Emergency Key Switch',
    price: 1500, 
    warranty: 'none',
  }, 
  { name: 'Door Buzzer',
    price: 350, 
    warranty: 'none',
  }, 
  { name: 'Wireless Doorbell',
    price: 1500, 
    warranty: 'none',
  }, 
  { name: 'Battery',
    price: 2500, 
    warranty: 'none',
  }, 
]